### ISSUE TITLE
The way to distinguish framework versions

### ISSUE THREAD

**Issue by SergeAx** [xssc/awesome-slim#18]
Hi! Thanks for awesome list, helps sometimes in my work and self-learning.

It would be great, though, to know a target version of Slim Framework before clicking any link. Saves time, sometimes a lot of it to check out every sample manually.

Currently we have Slim 2 and Slim 3, with Slim 4 underway. I've checked some other awesome lists and found two basic tagging systems: with text tag before link and with colored emoji after.

First way should look like this:

 * `[3.x]` [Some Slim 3 link](http://example.com/)
 * `[2.x]` [Some other link](http://example.com/)

Note fixed width code markdown in tags to ensure same alignment at any font and system. It also looks neat with grayed round-cornered background.

Emoji tag system:

Legend: 🔴 - Slim 2, 🔶 - Slim 3

 * 🔶 [Some Slim 3 link](http://example.com/)
 * 🔴 [Some other link](http://example.com/)

Emoji are fun, but this system has a number of downsides:

 * Not enough same-color symbols in current emoji pool to cover more than 4 different versions
   * Can't use different colors because of TTY-terminals/colorblind people
   * Other perfect keycap emoji are unsupported by lots of systems and/or browsers. [Check yours](http://emojipedia.org/keycap-digit-zero/). 
 * May be incompatible with some terminal clients or legacy editors/systems
 * Needs legend string

So I suggest to use text tags system. If it's okay with you, I would make a PR with initial tags and contribution guide amendments.

**Comment by xssc** [comment]
I would love a pull request for this! And yes, I agree the text tags are much better than the emojis.

**Comment by SergeAx** [comment]
Okay. check this out.

**Comment by SergeAx** [comment]
Hey, @xssc, have you had time to check my PR? Is something wrong with it?

**Comment by xssc** [comment]
Sorry for the long time gap... Catching up on this repo!, merged #19
